    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Decode Keystore
        script: |
          # Ye line text ko file mein badal degi
          echo $CM_KEYSTORE | base64 --decode > "$CM_BUILD_DIR/rto_release.jks"
      - name: Build and Sign Release APK
        script: |
          chmod +x ./gradlew
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file="$CM_BUILD_DIR/rto_release.jks" \
            -Pandroid.injected.signing.store.password=$CM_KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$CM_KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$CM_KEY_PASSWORD
