workflows:
  android-workflow:
    name: RtoEChallan Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.rte.challan"
      java: 17
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Debug APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - vikash6759ub@gmail.com
        notify:
          success: true
          failure: true
